### ISSUE TITLE
Null values in table component

### ISSUE THREAD

**Issue by BT2** [ivylabs/IvyBC#1]
Hi guys, How to handle in Bootstrap Table Component to not show "null" when the value from query is empty? 

Here is example:
![null](https://cloud.githubusercontent.com/assets/9214484/4629236/16ef6a86-53a2-11e4-9b15-1f81fd23f924.png)

**Comment by latinojoel** [comment]
Hi @BT2,

Thanks for report this issue. Marketplace will be updated soon with the new version that you can get from this url: http://sourceforge.net/projects/ivylabs/files/Pentaho/BI%20Server/Ivy%20IS%20Bootstrap%20Components%20%28free%20version%29/1.0.1%20%28free%20version%29/IvyBC.zip/download

Cheers.
